### ISSUE TITLE
🐛 [BUG] - Profiles not saving

### ISSUE THREAD

**Issue by sirdonpiano** [ClassicUO/classicuo-web#107]
### Description

When using the new retail client, creating a new profile, updating it and logging off the profile is lost. Similarly, the default profile changes are not saving either, but the default profile still exists.

### Reproduction steps

```bash
1. Create new or clone profile
2. Make changes to settings
3. Log off, close tab, etc
4. Log back in and profiles and changes are gone
```

### Browsers

Chrome

### OS

Mac

**Comment by Amylizy** [comment]
I am having this same problem. I have tried making macros and setting up things like my window size and nothing is saving between logging out of the game client.  I really don't want to play if I have to set up all my macros every single time.
Please let us know what might be happening?
Thank you.
