### ISSUE TITLE
🐛 [BUG] - Client has to be closed and restarted when an update is pushed

### ISSUE THREAD

**Issue by sirdonpiano** [ClassicUO/classicuo-web#126]
### Description

Whenever an update is pushed it seems to disconnect you and when you try to reconnect it'll hang at verifying indefinitely until you close out completely and start a fresh tab. 

Is there a way to make this process a bit more graceful? I can only imagine a scenario in which a whole guild runs web, is participating in content, and all simultaneously get connected and have to reopen all of their clients to log back in.

### Reproduction steps

```bash
See desc.
```

**Comment by andreakarasho** [comment]
Updates can't cause any disconnection. Probably yours is an external issue
