### ISSUE TITLE
🐛 [BUG] - Status bars of killed creatures

### ISSUE THREAD

**Issue by IrbisAsh** [ClassicUO/classicuo-web#130]
### Description

<img width="1512" alt="Screenshot 2024-10-14 at 8 35 19 PM" src="https://github.com/user-attachments/assets/0c253cc1-6a3e-4665-8eb1-9a76b054e3a5">
Status bars of killed creatures
when trying close them with right click, it's not working

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Mac

**Comment by andreakarasho** [comment]
Press "ALT + right click" to close the singole bar
