### ISSUE TITLE
🐛 [BUG] - <'Say' macro broken>

### ISSUE THREAD

**Issue by Ouija9835** [ClassicUO/classicuo-web#132]
### Discord Username

Ouija9835

### Description

The 'Say' macro in game does not offer a place for text. Furthermore, selecting, assigning a hotkey and attempting to use will cause the web client to freeze.

### Reproduction steps

```bash
1. Launch Client and signin
2. Go to 'hotkeys'
3. Select 'Macros'
4. Select 'add macro'
5. Select the 'Say' macro
6. No ability to input 'Say' text
7. Assigning a hotkey and using in game will cause client to freeze.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Windows

**Comment by andreakarasho** [comment]
Fixed
