### ISSUE TITLE
🐛 [BUG] - <Dragon Turtle is Broken>

### ISSUE THREAD

**Issue by SquareBovine** [ClassicUO/classicuo-web#134]
### Discord Username

ZozmaLS

### Description

As soon as I get on the same screen with the Dragon Turtle (Champ Boss, Eodon) the video and sound starts glitching/skipping and it's unplayable.

### Reproduction steps

```bash
1. Go to 'Dragon turtle habitat'
2. Work Champ spawn all the way until Dragon Turtle spawns.
3. Get on the same screen as Dragon turtle.
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Microsoft Edge

### OS

Windows

**Comment by andreakarasho** [comment]
Should be fixed
