### ISSUE TITLE
🐛 [BUG] - Bandage Target gets stuck on LastTarget

### ISSUE THREAD

**Issue by Tyskoll** [ClassicUO/classicuo-web#150]
### Discord Username

Jimmy the Hand or Selenus

### Description

When using 
**Macros**->**BandageTarget** action, or,
**Hotkey**->**Combat**->**Bandage**->**Target** 

it can become stuck on **LastTarget** and will always attempt to use bandages on **LastTarget** instead of offering the target cursor as it does when not "stuck".
This consistently happens with a pet that is healed to full and has the macro used on it.
This is not the expected behaviour.

A fix to this/a new **UseBandage** (with no targeting associated) as well as the inclusion of **ClearTarget** in Actions would be great.

### Reproduction steps

```bash
1. Create **BandageTarget** macro with: Action #1 **BandageTarget**
2. Use **BandageTarget** macro -> Manually target a pet that has full hp.
3. Use **BandageTarget** macro -> 
4. At this point the macro will smart/sticky target the **LastTarget** (noted by the health bar beneath it)

Expected result: 

Cursor waits for target like in first use.

Actual result:

Macro uses the bandage on the fully healed pet without manually clicking, it does not **WaitForTarget** (even with the insertion of this Action in to the macro)
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Windows

**Comment by andreakarasho** [comment]
Fixed.
The bandageTarget follows the "new target system" mechanic, which means you need to enabled it now.
That's how it will work:
if newTargetSystem.Serial is not set ==> dclick the bandage and wait for target cursor
else ==> target the newTargetSystem.Serial automatically.

You can unset the newtargetsystem.Serial pressing ESCAPE or you can switch to a different target
